version: '3.7'
services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80"

  backend:
    image: registry.openwt.com/coronapp/coronapp-backend:${CORONAPP_VERSION:-latest}
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=2107
      - SPRING_DATA_MONGODB_PASSWORD=
      - SPRING_DATA_MONGODB_DATABASE=bag
      - SECURITY_EXPORTER_USERNAME=exporter
      - SECURITY_EXPORTER_PASSWORD=password

  mongodb:
    image: mongo:4.2.0-bionic
    ports:
      - 27017
